name: metalink_flutter
description: Flutter UI components for link previews using the MetaLink package
version: 1.0.2
repository: https://github.com/omar-hanafy/metalink_flutter
topics:
  - link-preview
  - link-detector
  - url
  - link
  - metadata

environment:
  sdk: ^3.0.0
  flutter: ^3.24.4

dependencies:
  flutter:
    sdk: flutter
  
  # Core link extraction
  metalink: ^1.0.4
  
  # Required utilities
  url_launcher: ^6.3.1
  equatable: ^2.0.7
  flutter_helper_utils: ^6.0.2
  hive_ce_flutter: ^2.0.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 7.0.0

dependency_overrides: 
  metalink:
    git:
      ref: "main"
      url: https://github.com/jauntybrain/metalink

flutter:
  uses-material-design: true

screenshots:
  - description: 'Card styles link preview'
    path: screenshots/1.png
  - description: 'URL detection preview'
    path: screenshots/2.png
  - description: 'Controller usage preview'
    path: screenshots/3.png
  - description: 'Custom styles link preview'
    path: screenshots/4.png
